# .air.toml

[build]
  cmd = "go build -o ./tmp/main ./cmd/web"
  entrypoint = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  log = "air.log"

[log]
  time = true

[debug]
  enable = true

[watch]
  dir = "."
